[package]
name = "evercrypt_cryptolib"
version = "0.1.0"
edition = "2021"

[dependencies]
hacspec-lib = { git = "https://github.com/hacspec/hacspec", package = "hacspec-lib" }
crypto_utils = { path = "../crypto_utils" }
evercrypt = "0.0.10"
